In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2+cu121


### 1. Introduction to Tensors
Creating tensors
PyTorch tensors are created using 'torch.Tensor()'

In [81]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [82]:
scalar.ndim

0

In [83]:
# Get tensor back as Python int
scalar.item()

7

In [84]:
# Vector
vector  = torch.tensor([7,7])
vector

tensor([7, 7])

In [85]:
vector.ndim

1

In [86]:
vector.shape

torch.Size([2])

In [87]:
# Matrix
Matrix = torch.tensor([
    [7,8],
    [9,10]
])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [88]:
Matrix.ndim

2

In [89]:
Matrix[0], Matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [90]:
Matrix.shape

torch.Size([2, 2])

In [91]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [92]:
TENSOR.ndim

3

In [93]:
TENSOR.shape #[1,3,3] -> First bracket-purple (1), Second bracket-blue (2), Third Bracket-yellow (3) 

torch.Size([1, 3, 3])

In [94]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### 1.1. Random tensors
- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [95]:
# Create a random tensor of size
# random_numbers = torch.rand(3,4)
random_numbers = torch.rand(10,10,10)
random_numbers

tensor([[[8.7049e-02, 1.2135e-01, 8.5441e-01, 5.5493e-01, 4.4724e-01,
          6.0796e-01, 2.9867e-01, 4.2136e-01, 1.2623e-01, 5.6924e-01],
         [5.6325e-01, 5.0304e-01, 3.4297e-01, 5.0584e-01, 4.2037e-01,
          6.1751e-01, 1.5533e-01, 6.2064e-01, 4.4082e-01, 6.2484e-01],
         [7.7657e-01, 5.7876e-02, 1.6380e-01, 1.1698e-01, 1.9377e-01,
          8.9979e-02, 9.2821e-01, 1.7813e-01, 8.8107e-01, 3.4235e-01],
         [4.0639e-01, 9.0671e-01, 9.2850e-01, 6.3041e-01, 7.6933e-01,
          1.6371e-01, 6.7337e-01, 1.7413e-01, 8.4313e-01, 1.2654e-01],
         [9.1943e-01, 7.7460e-01, 8.4256e-01, 5.6680e-01, 2.0544e-01,
          9.5007e-01, 7.8041e-01, 6.2631e-01, 8.4448e-01, 7.8103e-01],
         [8.7993e-01, 6.9602e-02, 8.6750e-03, 6.9385e-01, 4.4355e-01,
          5.4685e-02, 2.2158e-01, 7.4944e-02, 8.4894e-01, 8.7824e-01],
         [5.6307e-01, 8.1192e-02, 3.4369e-01, 4.8881e-01, 9.1688e-01,
          7.6088e-01, 1.5869e-01, 4.6079e-01, 8.5944e-01, 7.0147e-01],
         [4.4

In [96]:
random_numbers.ndim

3

In [97]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colur (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [98]:
random_image_size_tensor

tensor([[[0.0069, 0.2402, 0.4657,  ..., 0.5138, 0.7079, 0.2867],
         [0.3453, 0.6213, 0.6013,  ..., 0.1215, 0.5079, 0.7136],
         [0.9672, 0.5970, 0.4650,  ..., 0.3658, 0.6596, 0.5460],
         ...,
         [0.8390, 0.4120, 0.6313,  ..., 0.7442, 0.1579, 0.7079],
         [0.9253, 0.0721, 0.9469,  ..., 0.4815, 0.0911, 0.8463],
         [0.3156, 0.2565, 0.3605,  ..., 0.4413, 0.3719, 0.8730]],

        [[0.9166, 0.9552, 0.9735,  ..., 0.9730, 0.1100, 0.1815],
         [0.5413, 0.3618, 0.1676,  ..., 0.2357, 0.0981, 0.6728],
         [0.4785, 0.6505, 0.7029,  ..., 0.7867, 0.8852, 0.5549],
         ...,
         [0.1253, 0.1881, 0.7485,  ..., 0.1120, 0.7624, 0.9300],
         [0.3408, 0.9308, 0.4139,  ..., 0.3060, 0.7084, 0.0657],
         [0.3265, 0.4439, 0.4206,  ..., 0.0371, 0.8385, 0.6509]],

        [[0.4221, 0.2768, 0.2736,  ..., 0.5660, 0.3240, 0.3043],
         [0.3919, 0.2521, 0.3898,  ..., 0.9555, 0.6634, 0.8618],
         [0.0322, 0.2753, 0.2107,  ..., 0.4705, 0.3580, 0.

### 1.2 Zeros and Ones
these are using for the masking process

In [99]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [100]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [101]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

### 1.3 Creating a range of tensors and tensors-like

In [102]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 1.4 Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

**ps.** Precision in computing

In [104]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # what datatype is the tensor (e.g. float32*, float64, float16*) <- Precision computing
                                device=None, # what device is tensor on (e.g. CPU, GPU, NPU, TPU)
                                requires_grad=False) # whether or not to track gradients with this operation
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [105]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor,float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [106]:
float_32_tensor*float_16_tensor # Errors not happened but massive neural network striking risk to u by this

tensor([ 9., 36., 81.])

In [107]:
int_32_tensor = torch.tensor([3,6,9,], dtype=torch.int32) # multiply other tensor : OK
# int_32_tensor = torch.tensor([3,6,9,], dtype=torch.int64) # multiply other tensor : OK
# int_32_tensor = torch.tensor([3,6,9,], dtype=torch.long)  # multiply other tensor : OK
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [108]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### **1.4 Advice! - Tensor attributes errors**

1. Tensors not right datatype - to do datatype from a tensor, [ **tensor.dtype** ]
2. Tensors not right shape - to get shape from a tensor,  [ **tensor.shape** ]
3. Tensors not on the right device - to get device from a tensor, [ **tensor.device** ]

In [109]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1205, 0.5147, 0.6169, 0.5351],
        [0.5946, 0.0347, 0.8396, 0.7542],
        [0.2289, 0.0607, 0.5133, 0.7292]])

In [110]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [111]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape    of tensor: {some_tensor.shape}')
print(f'Device   of tensor: {some_tensor.device}')

tensor([[0.1205, 0.5147, 0.6169, 0.5351],
        [0.5946, 0.0347, 0.8396, 0.7542],
        [0.2289, 0.0607, 0.5133, 0.7292]])
Datatype of tensor: torch.float32
Shape    of tensor: torch.Size([3, 4])
Device   of tensor: cpu


### 1.5 Manipulating Tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [112]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [113]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [114]:
tensor

tensor([1, 2, 3])

In [115]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [116]:
# Try Pytorch in-bulit function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [117]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### 1.6 Matrix multiplication

two main ways of performing multiplication 
1. element-wise multiplication
2. Matrix multiplication (dot product)

**TWO RULES:** 
1. the **inner dimensions must match: (matmul = @)
* '(3, 2) @ (3, 2)' won't work
* '(2, 3) @ (3, 2)' work
* '(3, 2) @ (2, 3)' work
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

*ps.* matrix multiplication : https://www.mathsisfun.com/algebra/matrix-multiplying.html    
*ps.* matrix multiplicaiton simulation : http://matrixmultiplication.xyz/



In [118]:
# element wise multiplication
print(tensor, '*', tensor)
print(f'Equals:{tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [119]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [120]:
tensor

tensor([1, 2, 3])

In [121]:
# Matrix multiplication by hand (dot product)
1*1 + 2*2 + 3*3

14

In [122]:
%%time
value =0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [123]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### **1.7 Advice! - Matrix Multiplication ( shape errors )**

In [124]:
try:
    # shape for matrix multiplication
    tensor_A = torch.tensor([[1,2],
                            [3,4],
                            [5,6]])
    tensor_B = torch.tensor([[7,10],
                            [8,11],
                            [9,12]])

    # torch.mm(tensor_A, tensor_B) # torch.mm = torch.matmul
    torch.mm(tensor_A, tensor_B)
except RuntimeError  as e:
    print(f'ERROR OCCURRED: {e}')

ERROR OCCURRED: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


To fix tensor shape issues, using a **transpose**  
A **transpose** switches the axes or dimensions of a given tensor

In [125]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [126]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [127]:
torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [128]:
# the matrix multiplication operation works when tensor_B is transpose
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: ( {tensor_A.shape} @ {tensor_B.shape} <- inner dimension must match')
print(f'Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shapes: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: ( torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shapes: torch.Size([3, 3])


### 1.8 Min, Max, mean, sum, etc (tensor aggregation)

In [129]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [130]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [131]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [132]:
# find the mean 
try:
    torch.mean(x)
except RuntimeError as e:
    print(f'ERRORS OCCURED: {e}\n')

# note: torch.mean() function requires a tensor of float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

ERRORS OCCURED: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long



(tensor(46.), tensor(46.))

In [133]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [134]:
# Find the positional min and max
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [135]:
# Find the position in tensor minimum 
print(f'position: {x.argmin()}, values:{x[x.argmin()]}, x.min: {x.min()}')

position: 0, values:1, x.min: 1


In [136]:
# Find the position in tensor maximum 
print(f'position: {x.argmax()}, values:{x[x.argmax()]}, x.min: {x.max()}')

position: 9, values:91, x.min: 91


### 1.9 Reshaping, Stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape   
* View      - return a view of an input of certain shape but keep the same memory
* Stacking  - Combing multiple tensors on top of each other (vstack) or side by side (hstack)
* **squeeze**   - remove all '1' dimensions from a tensor
* **unsqueeze** - add a 1 dimension to a target tensor
* Permute   - Return a view of the input with dimensions permuted (swapped) in a certain way

In [137]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [138]:
try:
    x_reshaped = x.reshape(2,9)
    x_reshaped, x_reshaped.shape
except RuntimeError as e:
    print(f'ERROR OCCURRED: {e}\n')

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape    

ERROR OCCURRED: shape '[2, 9]' is invalid for input of size 9



(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [139]:
# Add an extra dimension
try:
    x_reshaped = x.reshape(1,7)
    x_reshaped, x_reshaped.shape
except RuntimeError as e:
    print(f'ERROR OCCURRED: {e}\n')

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape    

ERROR OCCURRED: shape '[1, 7]' is invalid for input of size 9



(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [140]:
# Change the view
x_1 = torch.arange(1., 11.)
x_1, x_1.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [141]:
x_1_reshaped = x_1.reshape(5,2)
x_1_reshaped, x_1_reshaped.shape    

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [142]:
x_1_reshaped = x_1.reshape(2,5)
x_1_reshaped, x_1_reshaped.shape    

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [143]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [144]:
# Changing z change x (because a view of a tensor shares the same memory as the original)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [145]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [146]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [147]:
try:
    x_stacked = torch.stack([x,x,x,x], dim=2)
    x_stacked
except IndexError as e:
    print(f'ERROR OCCURRED:{e}')

ERROR OCCURRED:Dimension out of range (expected to be in range of [-2, 1], but got 2)


In [148]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f'Previous tensor : {x_reshaped}')
print(f'Previous shape : {x_reshaped.shape}')

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew shape : {x_squeezed}')
print(f'New shape : {x_squeezed.shape}')


Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New shape : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [149]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous tensor : {x_squeezed}')
print(f'Previous shape : {x_squeezed.shape}')

# Add an extra dimension from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew shape : {x_unsqueezed}')
print(f'New shape : {x_unsqueezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew shape : {x_unsqueezed}')
print(f'New shape : {x_unsqueezed.shape}')

Previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New shape : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape : torch.Size([9, 1])

New shape : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [150]:
# torch.permute - rearrange the dimension of a target tensor
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shift axis(or index) 0->1, 1->2, 2->0

print(f'Previous shape:{x_original.shape}')
print(f'New      shape:{x_permuted.shape}')

Previous shape:torch.Size([224, 224, 3])
New      shape:torch.Size([3, 224, 224])


### 1.10 Indexing (selecting data from tensors)
indexing with Pytorch = Numpy

In [151]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3) # make 1 box with 3x3 matrix
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [152]:
# Index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
# index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [154]:
# index on the most inner bracket (dim=last)
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [155]:
try:
    x[1][1][1], x[0][0][2]
except IndexError as e:
    print(f'ERROR OCCURRED:{e}')

x[0][1][1]

ERROR OCCURRED:index 1 is out of bounds for dimension 0 with size 1


tensor(5)

In [156]:
# ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [157]:
# all values of 0th and 1st dimensions but only index 1 and 2nd dimension
x[:,:,1],x[:,:,2],x[:,:,0]

(tensor([[2, 5, 8]]), tensor([[3, 6, 9]]), tensor([[1, 4, 7]]))

In [158]:
# index 0 and 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])