In [14]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2+cu121


### 2.1 Pytorch tensor and Numpy

* Data in numpy, want in Pytorch tensor -> '**torch.from_numpy(ndarray)**'
* Pytorch tensor -> '**torch.Tensor.numpy()**'


In [15]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [17]:
tensor_1 = torch.from_numpy(array).type(torch.float32) # converting from numpy -> pytorch default float64
array.dtype, tensor_1.dtype

(dtype('float64'), torch.float32)

In [18]:
# Change the value of array, 
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
# Change the tensor, what about numpy? (No sharing variables in memory)
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### 2.2 Reproducbility (random seed numbers)

To reduce the randomness in neural networks comes the concept of a **random seed**

In [21]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [22]:
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # manual_seed is only working on one function
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### 2.3 Accessing a GPU
GPUs = faster computation on numbers (CUDA + nvidia + pytorch)

In [23]:
!nvidia-smi

Sun Apr  7 01:01:20 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.52                 Driver Version: 551.52         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8             10W /   95W |    1423MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [24]:
# Check for GPU access
torch.cuda.is_available()

True

In [25]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [26]:
# Putting tensors on the GPU
tensor = torch.tensor([1,2,3], device='cpu')
print(tensor, tensor.device)

# Moving to the GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# If tensor is on GPU, can't transform it to numpy
try:
    tensor_on_gpu.numpy()
except TypeError as e:
    print(f"ERROR OCCURRED:{e}")

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

tensor([1, 2, 3]) cpu
ERROR OCCURRED:can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


array([1, 2, 3], dtype=int64)